### ISSUE TITLE
Får Error 500 ved epost, når feil bør vera 404 (Bugzilla Bug 1197)

### ISSUE THREAD

**Issue by albbas** [giellatekno/oahpa#150]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 1197
Date: 2011-10-21T18:31:45+02:00
From: Ryan Johnson &lt;ryan.txanson&gt;
To:   Ryan Johnson &lt;ryan.txanson&gt;
CC:   @ciprian-NO, heli1401, @leneantonsen, marit.fjellheim, ryan.txanson, sissel.jama, Sylvia.Sparrock, toini.bergstrom, @Trondtr

Last updated: 2011-12-29T22:00:09+01:00

**Comment by albbas** [comment]
## Comment 5392
Date: 2011-10-21 18:31:45 +0200
From: Ryan Johnson &lt;ryan.txanson&gt;

Traceback (most recent call last):

 File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 127, in get_response
   return callback(request, **param_dict)

 File "/usr/lib/python2.6/site-packages/django/views/defaults.py", line 14, in page_not_found
   return http.HttpResponseNotFound(t.render(RequestContext(request, {'request_path': request.path})))

 File "/usr/lib/python2.6/site-packages/django/template/context.py", line 149, in __init__
   self.update(processor(request))

 File "/home/smaoahpa/smaoahpa/conf/context_processors.py", line 18, in grammarlinks
   from smadrill.forms import switch_language_code

 File "/home/smaoahpa/smaoahpa/smadrill/forms.py", line 10, in <module>
   from smadrill.game import relax

 File "/home/smaoahpa/smaoahpa/smadrill/game.py", line 4, in <module>
   from smaoahpa.smadrill.forms import *

 File "/home/smaoahpa/smaoahpa/smadrill/forms.py", line 10, in <module>
   from smadrill.game import relax

ImportError: cannot import name relax


<ModPythonRequest
path:/aarjel/morfac_p/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{},
META:{'AUTH_TYPE': None,
 'CONTENT_LENGTH': 0,
 'CONTENT_TYPE': None,
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'gzip,deflate',
 'HTTP_CONNECTION': 'Keep-alive',
 'HTTP_FROM': 'googlebot(at)googlebot.com',
 'HTTP_HOST': 'oahpa.uit.no',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
 'PATH_INFO': u'/aarjel/morfac_p/',
 'PATH_TRANSLATED': None,
 'QUERY_STRING': None,
 'REMOTE_ADDR': '66.249.72.17',
 'REMOTE_HOST': None,
 'REMOTE_IDENT': None,
 'REMOTE_USER': None,
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'oahpa.uit.no',
 'SERVER_PORT': 80,
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'mod_python'}>

**Comment by albbas** [comment]
## Comment 5393
Date: 2011-10-21 18:32:43 +0200
From: Ryan Johnson &lt;ryan.txanson&gt;

Eg arbeider med denne no, då kan me sjå nokre feilmeldingar.

Det ser ut som det er noko rart med django sine handler404- og handler500 funksjonar, og kanskje spesielt med mod_python. Eg prøver på virtuel maskina mi og då berre får ein 500 feil (som sender denne eposten) på første gongen eg besøkjer ei sida som ikkje eksisterar. Når eg trykkjer på refresh, får eg då 404.

**Comment by albbas** [comment]
## Comment 5394
Date: 2011-10-21 19:20:45 +0200
From: Ryan Johnson &lt;ryan.txanson&gt;

Fann feilen. Det var ein metode som er kalla til kvar view-funskjon som funka slik at det var ein circular import. Eg flytta ein annan funksjon til ein betre stad for å ungå dette, og det ser ut til å funka på virtuel maskina mi. Skal svn up på victorio nattartid i Noreg. :)
