### ISSUE TITLE
lcat.py does not tolerate redirecting output (Bugzilla Bug 685)

### ISSUE THREAD

**Issue by albbas** [giellatekno/oahpa#310]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 685
Date: 2008-05-05T10:09:23+02:00
From: @Trondtr (Originally created by @Trondtr)
To:   Saara Huhmarniemi &lt;saara.huhmarniemi&gt;
CC:   @leneantonsen, @Trondtr

Last updated: 2008-05-05T10:29:50+02:00

**Comment by albbas** [comment]
## Comment 2685
Date: 2008-05-05 10:09:23 +0200
From: @Trondtr

On victorio, everything is fine. On our local macs (with python 2.5.1), we  (both Lene 10.4.9 and Trond 10.5.1) get a nice output when we let it go to standard output:

python src/lcat.py -b d1 -f sme/xml/verbs.xml


But when redirected it to less, more, or a file, the output halts at the first Sámi letter, with the following message:

Traceback (most recent call last):
  File "src/lcat.py", line 118, in <module>
    print_entries(entries,all)
  File "src/lcat.py", line 63, in print_entries
    print ltext
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 1: ordinal not in range(128)
hupmat
boradit
buktit
(END) 

Without the pipe, the first 5 lines of output are as follows:

-bash-3.00$ python src/lcat.py -b d1 -f sme/xml/verbs.xml
hupmat
boradit
buktit
máhttit
vuodjit


As can be seen, the program halts at "máhttit".
